name: 'taetaetae Hello World'
inputs:
  token:
    description: 'Personal access token'
    required: true
  api-domain:
    required: false
    default: "api.github.com"
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'