on:
  workflow_dispatch:
  push:
   branches: 
     - 'rb-**'
     
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: action-test
        uses: taetaetae/change-summarizer@f/init
        with:
          token: ${{ secrets.TOKEN }}
      - run: echo "${{ steps.action-test.outputs.time }}"
        shell: bash
