on:
  workflow_dispatch:
  push:
   branches: 
     - 'rb-**'
     
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: action-test
        uses: taetaetae/helloWorld@v1.1
        with:
          token: ${{ secrets.TOKEN }}
      - run: echo ${{ steps.foo.outputs.diff-body }}
        shell: bash
